Adapta front a otimização no backend
parlametria/leggo-frontend pull request #553
Opened 2020-10-22 19:22 UTC by hadrizia

**Mudanças neste PR:** 

- Ajusta o front para receber o novo formato do resumo do progresso, criando novo store e state isolados para esses dados :woman_dancing:

2020-10-26 12:05 UTC, gileadekelvin commented on src/router.js
> +          // console.log(prop)
Sobrou um comentário :)

2020-10-26 12:06 UTC, gileadekelvin requested changes

2020-10-26 12:06 UTC, gileadekelvin commented on src/router.js
> +        if (Object.keys(progressos).length === 0) {
acredito que essa chamada também deve ser feita para o router path: '/:slug_interesse'

2020-10-26 19:58 UTC, hadrizia commented on src/router.js
> +        if (Object.keys(progressos).length === 0) {
feito! obrigada, gile!

2020-10-27 12:17 UTC, gileadekelvin approved these changes

2020-10-27 12:18 UTC, merged